[package]
name = "historical-loader"
version.workspace = true
edition.workspace = true

[dependencies]
market-types = { path = "../market-types" }
anyhow = { workspace = true }
serde_json = { workspace = true }
flate2 = { workspace = true }
